export const packagesData = [
  {
    Service: "Basic Package",
    Price: 6499,
    "E-Book Publishing": true,
    "Paperback/Hardcover": true,
    "Complementary Copies": 2,
    "Book Royalty": 70,
    Pages: "0-120",
    Revisions: 1,
    "Cover Design": "Basic",
    "YouTube Feature": "Basic",
    "Film Feature": false,
    "ISBN Assignment": true,
    "Author Assignment": true,
    "CopyEditing/ProofReading": "Basic",
    "Book Fair & Award Nomination": true,
    "Online Store Distribution": false,
    "Copyright Registration": "Basic",
    "PR Promotion": false,
    "Social Media Marketing": false,
    "Author Interview": false,
    "Audio Book": false,
    "International Book Launch": false,
    "Offline Promotion": false,
    Extras: "Certification of Authorship",
  },
  {
    Service: "Standard Package",
    Price: 9999,
    "E-Book Publishing": true,
    "Paperback/Hardcover": true,
    "Complementary Copies": 5,
    "Book Royalty": 80,
    Pages: "0-200",
    Revisions: 2,
    "Cover Design": "Basic",
    "YouTube Feature": "Standard",
    "Film Feature": "Basic",
    "ISBN Assignment": true,
    "Author Assignment": true,
    "CopyEditing/ProofReading": "Standard",
    "Book Fair & Award Nomination": true,
    "Online Store Distribution": true,
    "Copyright Registration": "Standard",
    "PR Promotion": "Basic",
    "Social Media Marketing": "Basic",
    "Author Interview": "Basic",
    "Audio Book": true,
    "International Book Launch": "Basic",
    "Offline Promotion": "Basic",
    Extras: "Certification + Medal + Membership Voucher",
  },
  {
    Service: "Premium Package",
    Price: 13999,
    "E-Book Publishing": true,
    "Paperback/Hardcover": true,
    "Complementary Copies": 10,
    "Book Royalty": 90,
    Pages: "0-250",
    Revisions: 5,
    "Cover Design": "Advanced",
    "YouTube Feature": "Premium",
    "Film Feature": "Premium",
    "ISBN Assignment": true,
    "Author Assignment": true,
    "CopyEditing/ProofReading": "Premium",
    "Book Fair & Award Nomination": true,
    "Online Store Distribution": true,
    "Copyright Registration": "Premium",
    "PR Promotion": "Advanced",
    "Social Media Marketing": "Advanced",
    "Author Interview": "Advanced",
    "Audio Book": true,
    "International Book Launch": "Advanced",
    "Offline Promotion": "Advanced",
    Extras: "Certification + Medal + Membership Voucher + Cup Letter",
  },
  {
    Service: "Elite Package",
    Price: 32999,
    "E-Book Publishing": true,
    "Paperback/Hardcover": true,
    "Complementary Copies": 25,
    "Book Royalty": 100,
    Pages: "0-600",
    Revisions: 8,
    "Cover Design": "Advanced",
    "YouTube Feature": "Elite",
    "Film Feature": "Elite",
    "ISBN Assignment": true,
    "Author Assignment": true,
    "CopyEditing/ProofReading": "Premium",
    "Book Fair & Award Nomination": true,
    "Online Store Distribution": true,
    "Copyright Registration": "Elite",
    "PR Promotion": "Extensive",
    "Social Media Marketing": "Extensive",
    "Author Interview": "Extensive",
    "Audio Book": true,
    "International Book Launch": "145+ countries",
    "Offline Promotion": "Elite",
    Extras:
      "Certification + Medal + Membership Voucher + Cup Letter + Surprise Gift Hamper",
  },
];
